BASE: [""]
TOOLBOX_MODE: "only_test"
TEST:
  METRICS: ["MAE", "RMSE", "MAPE", "Pearson", "SNR", "BA"]
  USE_LAST_EPOCH: False
  DATA:
    FS: 30
    DATASET: UBFC-rPPG-h264
    DO_PREPROCESS: False
    DATA_FORMAT: NCDHW
    DATA_PATH: "/home/zyuanli/dev/lib/data/UBFC-rPPG-CRF22"
    CACHED_PATH: "/home/zyuanli/dev/lib/data/UBFC-rPPG-CRF22-cache"
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ["DiffNormalized"]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: "Y5F"
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  NAME: PhysMamba
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: True
    WINDOW_SIZE: 30
  MODEL_PATH: "./final_model_release/UBFC-rPPG_PhysMamba_DiffNormalized.pth"
